spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: com.example.treinamentokafka.model
